// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FOSSIL","status":true,"description":"Fossil is an interoperability layer for RMMZ, designed to make MV plugins work in MZ. \r\nSo far, we support over 300 plugins.  You can help!","parameters":{}}
];
